name: github release
on:
  workflow_call:
    inputs:
      update:
        required: false
        type: boolean
        default: false
jobs:
  create-gh-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get -y install jq
          python -m pip install pip -U
          pip install tox yq
      - name: Pack Shell
        if: ${{ inputs.update == false }}
        env:
          TOXENV: pack
        run: tox
      - name: Get Linux dependencies
        uses: actions/download-artifact@v3
        with:
          name: linux-dependencies
          path: linux-dependencies
      - name: Get Windows dependencies
        uses: actions/download-artifact@v3
        with:
          name: windows-dependencies
          path: windows-dependencies
      - name: Set envs
        run: |
          version="$(yq -r .metadata.template_version shell-definition.yaml)"
          repo_owner=${{ github.repository }}
          index=`expr index "$repo_owner" /`
          repo=${repo_owner:index}
          echo "TAG=$version" >> $GITHUB_ENV
          echo "REPO=$repo" >> $GITHUB_ENV
      - name: Pack dependencies
        run: |
          mkdir -p dist  # if we don't pack Shell the folder will not be created
          zip -j dist/cloudshell-$REPO-dependencies-win-package-$TAG.zip windows-dependencies/*
          zip -j dist/cloudshell-$REPO-dependencies-linux-package-$TAG.zip linux-dependencies/*
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "dist/*"
          draft: true
          name: ${{ env.REPO }} ${{ env.TAG }}
          tag: ${{ env.TAG }}
          commit: master
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          updateOnlyUnreleased: ${{ inputs.update == false }}
